# Generated by Django 4.2.11 on 2024-05-13 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encryption_Cle',
            fields=[
                ('idCle', models.AutoField(primary_key=True, serialize=False)),
                ('cle_privee_rsa', models.BinaryField()),
                ('cle_publique_rsa', models.BinaryField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
