# Generated by Django 5.0.5 on 2024-06-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_alter_userfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryption_cle',
            old_name='idCle',
            new_name='id',
        ),
        migrations.AddField(
            model_name='encryption_cle',
            name='salt',
            field=models.TextField(default='default_salt_value'),
        ),
        migrations.AlterField(
            model_name='encryption_cle',
            name='cle_privee_rsa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='encryption_cle',
            name='cle_publique_rsa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='encryption_cle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
